{
 "title": "Overview",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2025-11-17T00:00:00.000Z" },
 "panels": [
  {
   "title": "Tổng lợi nhuận",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT SUM(total_revenue) FROM fact_sales LIMIT 50 "
    }
   ]
  },
  {
   "title": "Tổng lợi nhuận thuần ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT SUM(gross_profit) FROM fact_sales LIMIT 50 "
    }
   ]
  },
  {
   "title": "Biên lợi nhuận",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  SUM(gross_profit) / SUM(total_revenue) * 100 AS gross_margin_percent\r\nFROM fact_sales;\r\n"
    }
   ]
  },
  {
   "title": "Tổng số đơn hàng",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT invoice_id) AS total_orders\r\nFROM fact_sales;\r\n"
    }
   ]
  },
  {
   "title": "Giá tiền trung bình của mỗi hóa đơn",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  SUM(total_revenue) / COUNT(DISTINCT invoice_id) AS avg_order_value\r\nFROM fact_sales;\r\n"
    }
   ]
  },
  {
   "title": "Tổng số khách hàng đã giao dịch ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT customer_key) AS total_customers\r\nFROM fact_sales;\r\n"
    }
   ]
  },
  {
   "title": "Doanh thu theo ngày",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  invoice_date AS date,\r\n  SUM(total_revenue) AS \"doanh thu\"\r\nFROM fact_sales\r\nGROUP BY invoice_date\r\nORDER BY invoice_date;\r\n"
    }
   ]
  },
  {
   "title": "Doanh thu theo cửa hàng",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  b.branch_name,\r\n  SUM(f.total_revenue) AS revenue\r\nFROM fact_sales f\r\nJOIN dim_branches b\r\n  ON f.branch_key = b.branch_key\r\nGROUP BY b.branch_name\r\nORDER BY revenue DESC;\r\n"
    }
   ]
  },
  {
   "title": "Doanh thu theo tháng",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', invoice_date) AS month,\r\n  SUM(total_revenue) AS revenue\r\nFROM fact_sales\r\nGROUP BY month\r\nORDER BY month;\r\n"
    }
   ]
  },
  {
   "title": "Doanh thu của từng cửa hàng theo tháng",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  b.branch_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_branches b\r\n  ON f.branch_key = b.branch_key\r\nWHERE f.branch_key = 'CN_MAIN'\r\nGROUP BY\r\n  month,\r\n  b.branch_name\r\nORDER BY month;\r\n"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  b.branch_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_branches b\r\n  ON f.branch_key = b.branch_key\r\nWHERE f.branch_key = 'PTK06'\r\nGROUP BY\r\n  month,\r\n  b.branch_name\r\nORDER BY month;\r\n"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  b.branch_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_branches b\r\n  ON f.branch_key = b.branch_key\r\nWHERE f.branch_key = 'PTK08'\r\nGROUP BY\r\n  month, \r\n  b.branch_name\r\nORDER BY month;\r\n"
    }
   ]
  },
  {
   "title": "Phân tích doanh thu tăng trưởng theo tháng",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "WITH monthly_revenue AS (\r\n  SELECT\r\n    DATE_TRUNC('month', invoice_date) AS month,\r\n    SUM(total_revenue) AS revenue\r\n  FROM fact_sales\r\n  GROUP BY month\r\n)\r\nSELECT\r\n  month,\r\n  revenue,\r\n  revenue - LAG(revenue) OVER (ORDER BY month) AS mom_diff,\r\n  ROUND(\r\n    (revenue - LAG(revenue) OVER (ORDER BY month))\r\n    / LAG(revenue) OVER (ORDER BY month) * 100,\r\n    2\r\n  ) AS mom_growth_pct\r\nFROM monthly_revenue\r\nORDER BY month;\r\n"
    }
   ]
  },
  {
   "title": "Doanh thu theo năm",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('year', invoice_date) AS year,\r\n  SUM(total_revenue) AS revenue\r\nFROM fact_sales\r\nGROUP BY year\r\nORDER BY year;\r\n"
    }
   ]
  },
  {
   "title": "Khách hàng chi nhiều nhất",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 62 },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  c.customer_name AS \"Khách hàng\",\r\n  c.phone AS \"SĐT\",\r\n  SUM(f.total_revenue) AS \"Tổng chi tiêu\"\r\nFROM fact_sales f\r\nJOIN dim_customers c ON f.customer_key = c.customer_key\r\nWHERE $__timeFilter(f.transaction_time)\r\nGROUP BY 1, 2\r\nORDER BY 3 DESC\r\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Top 5 sản phẩm có doanh thu cao nhất",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:đ:suffix" } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  p.product_name,\r\n  SUM(f.total_revenue) AS revenue\r\nFROM fact_sales f\r\nJOIN dim_products p\r\n  ON f.product_key = p.product_key\r\nGROUP BY p.product_name\r\nORDER BY revenue DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Doanh thu từng tháng của top 5 sản phẩm bán chạy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  p.product_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_products p\r\n  ON f.product_key = p.product_key\r\nWHERE f.product_key = 'BCCORGANIC'\r\nGROUP BY\r\n  month,\r\n  p.product_name\r\nORDER BY month;\r\n"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  p.product_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_products p\r\n  ON f.product_key = p.product_key\r\nWHERE f.product_key = 'BCC008'\r\nGROUP BY\r\n  month,\r\n  p.product_name\r\nORDER BY month;\r\n"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  p.product_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_products p\r\n  ON f.product_key = p.product_key\r\nWHERE f.product_key = 'SP000063'\r\nGROUP BY\r\n  month,\r\n  p.product_name\r\nORDER BY month;\r\n"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  p.product_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_products p\r\n  ON f.product_key = p.product_key\r\nWHERE f.product_key = 'BM-1'\r\nGROUP BY\r\n  month,\r\n  p.product_name\r\nORDER BY month;\r\n"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', f.invoice_date) AS month,\r\n  p.product_name,\r\n  SUM(f.total_revenue) AS monthly_revenue\r\nFROM fact_sales f\r\nJOIN dim_products p\r\n  ON f.product_key = p.product_key\r\nWHERE f.product_key = 'SP000109'\r\nGROUP BY\r\n  month,\r\n  p.product_name\r\nORDER BY month;\r\n"
    }
   ]
  },
  {
   "title": "Các sản phẩm bán ra được sắp xếp theo phần trăm",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  p.product_name,\r\n  SUM(f.total_revenue) AS revenue,\r\n  ROUND(\r\n    SUM(f.total_revenue)\r\n    / SUM(SUM(f.total_revenue)) OVER () * 100,\r\n    2\r\n  ) AS revenue_pct\r\nFROM fact_sales f\r\nJOIN dim_products p\r\n  ON f.product_key = p.product_key\r\nGROUP BY p.product_name\r\nORDER BY revenue DESC;\r\n"
    }
   ]
  }
 ]
}