{
 "title": "Report ERP",
 "time": { "from": "2023-12-31T17:00:01.000Z", "to": "2025-12-07T16:59:57.000Z" },
 "panels": [
  {
   "title": "Tổng tồn kho",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  SUM(total_inventory_value) AS \"Tổng giá trị kho\"\r\nFROM fact_inventory_daily\r\n"
    }
   ]
  },
  {
   "title": "Sản phẩm sắp hết",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  p.product_name AS \"Sản phẩm\",\r\n  b.branch_name AS \"Kho\",\r\n  i.quantity_on_hand AS \"Tồn kho\"\r\nFROM fact_inventory_daily i\r\nJOIN dim_products p ON i.product_key = p.product_key\r\nJOIN dim_branches b ON i.branch_key = b.branch_key\r\nWHERE i.snapshot_date = (SELECT MAX(snapshot_date) FROM fact_inventory_daily)\r\n  AND i.quantity_on_hand < 10 -- Ngưỡng cảnh báo\r\nORDER BY 3 ASC"
    }
   ]
  },
  {
   "title": "Tồn kho",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  b.branch_name AS \"Kho/Cửa hàng\",\r\n  SUM(i.total_inventory_value) AS \"Giá trị tồn kho\"\r\nFROM fact_inventory_daily i\r\nJOIN dim_branches b ON i.branch_key = b.branch_key\r\nWHERE i.snapshot_date = (SELECT MAX(snapshot_date) FROM fact_inventory_daily)\r\nGROUP BY 1\r\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Khách hàng chi nhiều nhất",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  c.customer_name AS \"Khách hàng\",\r\n  c.phone AS \"SĐT\",\r\n  SUM(f.total_revenue) AS \"Tổng chi tiêu\"\r\nFROM fact_sales f\r\nJOIN dim_customers c ON f.customer_key = c.customer_key\r\nWHERE $__timeFilter(f.transaction_time)\r\nGROUP BY 1, 2\r\nORDER BY 3 DESC\r\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Tổng Doanh thu:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT sum(total_revenue) as \"Tổng Doanh thu\"\r\nFROM fact_sales\r\nWHERE $__timeFilter(transaction_time)"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT count(invoice_id) as \"Số đơn hàng\"\r\nFROM fact_sales\r\nWHERE $__timeFilter(transaction_time)"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT \r\n  (SUM(gross_profit) / NULLIF(SUM(total_revenue), 0)) * 100 as \"Biên lợi nhuận %\"\r\nFROM fact_sales\r\nWHERE $__timeFilter(transaction_time)"
    }
   ]
  },
  {
   "title": "Biểu đồ doanh thu và lợi nhuận",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT\r\n  $__timeGroup(transaction_time, '24h') AS time, -- Gom nhóm theo giờ (hoặc ngày tùy zoom)\r\n  SUM(total_revenue) AS \"Doanh thu\",\r\n  SUM(gross_profit) AS \"Lợi nhuận gộp theo ngày\"\r\nFROM fact_sales\r\nWHERE $__timeFilter(transaction_time)\r\nGROUP BY 1\r\nORDER BY 1"
    },
    {
     "dataset": "erp_serving",
     "rawSql": "SELECT sum(total_revenue) as \"Tổng Doanh thu\"\r\nFROM fact_sales\r\nWHERE $__timeFilter(transaction_time)"
    }
   ]
  }
 ]
}